export const scanKindsMigration = `
ALTER TABLE scans ADD COLUMN images INTEGER NOT NULL DEFAULT 1;
ALTER TABLE scans ADD COLUMN videos INTEGER NOT NULL DEFAULT 1;
ALTER TABLE scans ADD COLUMN audio INTEGER NOT NULL DEFAULT 1;
`;
